# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170723_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('car_needed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='home_address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='state',
            new_name='home_state',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='zipcode',
            new_name='home_zipcode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='help_status',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='ride_needed',
        ),
        migrations.AddField(
            model_name='profile',
            name='car_license_plate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='car_license_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='driver_license',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='driver_license_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('SR', 'Senior'), ('VR', 'Volunteer'), ('BH', 'Both')], default='SR', max_length=2),
        ),
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASD', 'Assigned'), ('CMD', 'Completed')], default='NEW', max_length=3),
        ),
        migrations.AddField(
            model_name='service',
            name='zipcode',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(choices=[('HOME', 'Home'), ('TRIP', 'Trip'), ('OTHER', 'Other')], default='HOME', max_length=5),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ServiceType'),
        ),
        migrations.AlterField(
            model_name='service',
            name='special_instructions',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_city',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='service_types',
            field=models.ManyToManyField(blank=True, to='core.ServiceType'),
        ),
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.City'),
            preserve_default=False,
        ),
    ]
