# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170725_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='home_city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
