# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170725_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('location', models.CharField(choices=[('HOME', 'Home'), ('TRIP', 'Trip'), ('OTHER', 'Other')], default='HOME', max_length=5)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASD', 'Assigned'), ('CMD', 'Completed')], default='NEW', max_length=3)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zipcode', models.CharField(blank=True, max_length=9)),
                ('urgency', models.CharField(blank=True, max_length=100)),
                ('special_instructions', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='ServiceType',
            new_name='TaskType',
        ),
        migrations.RemoveField(
            model_name='service',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='service_types',
            new_name='task_types',
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('SENIOR', 'Senior'), ('VOLUNTEER', 'Volunteer'), ('BOTH', 'Both')], default='SENIOR', max_length=9),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='task',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TaskType'),
        ),
    ]
