# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170726_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
